### ISSUE TITLE
melodic command line usage

### ISSUE THREAD

**Issue by arii** [ros-visualization/rqt_robot_dashboard#3]
There doesn't appear to be any executable to launch the dashboard for ros-melodic--- there is no tab complete on `rosrun rqt_robot_dashboard `.  

If I try to do `rosrun rqt_robot_dashboard rqt_robot_dashboard` I get a no executable found error. Is there a new way for launching the dashboard?

**Comment by dirk-thomas** [comment]
Afaik there has never been an executable for this rqt plugin. You should be able to start `rqt` and then open the plugin using the graphical user interface.

**Comment by DLu** [comment]
There isn't a dashboard executable because this is more of a toolbox with which to build your own executable like http://wiki.ros.org/rqt_pr2_dashboard

**Comment by arne48** [comment]
This question should be answered and I think we can close this issue.
